services:
  homeassistant:
    image: ${HA_IMAGE:-ghcr.io/home-assistant/home-assistant:stable}
    restart: unless-stopped
    volumes:
      - ${HA_CONFIG_PATH}:/config
      - /etc/localtime:/etc/localtime:ro
    ports:
      - ${HA_PORT}
    user: root

  wyoming-whisper:
    image: rhasspy/wyoming-whisper
    command: --model medium --language no
    restart: unless-stopped
    volumes:
      - ${WYOMING_WHISPER_DATA_PATH}:/data
    ports:
      - 10300:10300

  wyoming-openwakeword:
    image: rhasspy/wyoming-openwakeword
    command: --preload-model 'alexa'
    restart: unless-stopped
    ports:
      - 10400:10400

  esphome:
    image: esphome/esphome:latest
    volumes:
      - ${ESPHOME_CONFIG_PATH}:/config
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 6052:6052
    #devices:
      #- ${ESPHOME_USB_DEVICE}
    restart: unless-stopped

