services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 127.0.0.1:8123:8123
    user: root

  wyoming-whisper:
    image: rhasspy/wyoming-whisper
    command: --model medium --language no
    restart: unless-stopped
    ports:
      - 10300:10300

  wyoming-openwakeword:
    image: rhasspy/wyoming-openwakeword
    command: --preload-model 'alexa'
    restart: unless-stopped
    ports:
      - 10400:10400

  esphome:
    image: esphome/esphome:latest
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 6052:6052
    #devices:
      #- ${ESPHOME_USB_DEVICE}
    restart: unless-stopped

